import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Login from '../components/Login'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Autheticated with Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login /> 

      
    </div>
  )
}

export default Home
